from .Ui_MainWindow import Ui_MainWindow
from .Ui_AddCustomerDialog import Ui_AddCustomerDialog
from .Ui_CustomerListItem import Ui_CustomerListItem
from .Ui_DayPrice import Ui_DayPrice
from .Ui_History import Ui_History
from .Ui_HistoryListItem import Ui_HistoryListItem
from .Ui_LineEditDialog import Ui_LineEditDialog
from .Ui_Login import Ui_Login
from .Ui_Customers import Ui_Customers
from .Ui_NavBar import Ui_NavBar
from .Ui_CarStatus import Ui_CarStatus
from .Ui_NavigationTree import Ui_NavigationTree
from .Ui_NewCarDialog import Ui_NewCarDialog
from .Ui_RentCustomerWidget import Ui_RentCustomerWidget
from .Ui_RentedCarsByCustomers import Ui_RentedCarsByCustomers
from .Ui_RentFormular import Ui_RentFormular
from .Ui_SimpleDialog import Ui_SimpleDialog
from .Ui_Statistic import Ui_Statistic
from .Ui_TreePriceWidget import Ui_TreePriceWidget
from .Ui_TreeStatusWidget import Ui_TreeStatusWidget
